### ISSUE TITLE
proxy-entity-per-url

### ISSUE THREAD

**Issue by agoddard** [sensu/http-checks#11]
For use cases where you
A) have a number of URLs to check, and for each URL you would like to monitor, you would like to generate a proxy entity
or
B) have a number of URLs to check, and for each target domain you would like to monitor, you would like to generate a proxy entity

it would be helpful to have functionality whereby the check made use of the local agent HTTP API to generate check results with proxy entities for each monitored endpoint. Presently this would require significant duplication of check configuration.

A possible input to the check could be a series of endpoint with a minimum of 1) HTTP URI to check 2) proxy entity name for endpoint, and optional params such as expected http status code, or other data to be passed to the http check during execution.

**Comment by jspaleta** [comment]
Do you just want to generate proxy entities, or do you want to generate handable events for each url?

lets start with a list of urls like this:
http://exampleA.com/first
http://exampleA.com/third
http://exampleA.com/fifth
http://exampleB.com/second
http://exampleB.com/fourth
http://exampleC.com/nope

Do you want just proxy entities generated for exampleA.com exampleB.com exampleC.com?

Or do you want events generated for each of those url checks?
If so do you want all those events to be potentially handled by different handlers?

**Comment by calebhailey** [comment]
Closing with recommendation to use the new Sensu check multiplexer, a reusable check utility for multi-execution of _any_ check command. See here for more info: https://github.com/sensu/sensu-check-multiplexer
